### PR TITLE
fix #15

### LINKED ISSUE #15: Feature suggestion: find unused imports
A feature I'd like to see and would find very useful would be the ability to scan a file for any imports that are unused, with options for either highlighting them (con: user has to manually remove them, pro: false positives caught by user) or optionally to auto-remove (con: potential for false positives).

### PR DESCRIPTION
**Pull request by rrd108**

### CODE REVIEW

**Comment by rrd108** [comment]
Done. I think the only thing what is missing to add the 2 highlight action to the readme.

**Comment by MehediDracula** [comment]
@rrd108 Excellent job. Thanks for your all contributions :blush:

**Comment by pedzed** [comment]
It would be nice if you could be more descriptive in your PR's.
image

Anyway, thank you so much for this!

**Comment by rrd108** [comment]
sure :-) i will

**Pull request merged**
