### PR TITLE
fix #37

### LINKED ISSUE #37: Highlight not imported classes
I think highlighting not imported classes would be a nice feature. If you agree I can implement it.

### PR DESCRIPTION
**Pull request by rrd108**

### CODE REVIEW

**Comment by MehediDracula** [comment]
Nice work. I think a hover message would be a nice addition as well.

**Comment by MehediDracula** [comment]
@rrd108 Looks like few previous commits are also pushed in this PR. Can you please send a new PR without those old commits?

**Comment by rrd108** [comment]
@MehediDracula Sure. I just do not know how to do it... We have no conflicts, so otherwise it can be merged.

**Comment by MehediDracula** [comment]
It's alright. I'll fix it once I'm free. Thanks for the PR!

**Pull request merged**
